class NpcModel < ApplicationRecord
  validates :alignment,
            :ancestry,
            :archetype_name,
            :archetype_desc,
            :armor_class,
            :background_equipment,
            :background_extra_languages,
            :background_name,
            :personality_personality,
            :personality_ideal,
            :personality_bond,
            :personality_flaw,
            :skill_proficiency_one,
            :skill_proficiency_two,
            :background_tool_proficiency_one,
            :background_tool_proficiency_two,
            :character_class,
            :equipment_extras,
            :gold,
            :gender,
            :hit_dice,
            :initiative,
            :languages,
            :level,
            :name,
            :proficiencies_armor,
            :proficiencies_weapons,
            :proficiencies_tools,
            :size,
            :speed,
            :core_modifiers_str_mod,
            :core_modifiers_dex_mod,
            :core_modifiers_con_mod,
            :core_modifiers_int_mod,
            :core_modifiers_wis_mod,
            :core_modifiers_cha_mod,
            :core_scores_str,
            :core_scores_dex,
            :core_scores_con,
            :core_scores_int,
            :core_scores_wis,
            :core_scores_cha,
            :hit_points,
            :dex_attack,
            :str_attack,
            :proficiency_bonus,
            :passive_perception,
            :saving_throws_str,
            :saving_throws_dex,
            :saving_throws_con,
            :saving_throws_int,
            :saving_throws_wis,
            :saving_throws_cha,
            :skills_proficiencies,
            :skills_acrobatics,
            :skills_animal_handling,
            :skills_arcana,
            :skills_athletics,
            :skills_deception,
            :skills_history,
            :skills_insight,
            :skills_intimidation,
            :skills_investigation,
            :skills_medicine,
            :skills_nature,
            :skills_perception,
            :skills_performance,
            :skills_persuasion,
            :skills_religion,
            :skills_sleight_of_hand,
            :skills_stealth,
            :skills_survival,
            :spell_slots,
            :sub_ancestry,
            :traits,
            :vision,
            :is_saved, presence: true

  has_many :npc_model_armors, dependent: :destroy
  has_many :armors, through: :npc_model_armors
  has_many :npc_model_packs, dependent: :destroy
  has_many :packs, through: :npc_model_packs
  has_many :npc_model_spells, dependent: :destroy
  has_many :spells, through: :npc_model_spells
  has_many :npc_model_weapons, dependent: :destroy
  has_many :weapons, through: :npc_model_weapons

  has_many :user_npc_models, dependent: :destroy
  has_many :users, through: :user_npc_models
end
